# markdown
highlighter: rouge
markdown: redcarpet
redcarpet:
  extensions:
  - with_toc_data

exclude:
- ".rbenv-version"
- README.md
- CONTRIBUTING.md
- LICENSE.md

# Site metadata
name: HTTPS for .gov
description: "Resources, best practices, and case studies for deploying HTTPS in the federal government."


# GitHub information
repo_name: https
branch: gh-pages
gh_org: GSA
url: https://https.cio.gov

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: HTTPS for .gov
  url: ""
  internal: true
- text: FAQ
  url: faq/
  internal: true
- text: Strict Transport Security
  url: hsts/
  internal: true
- text: Technical Concepts
  url: technical-concepts/
  internal: true
- text: Resources
  url: resources/
  internal: true

# Style Variables
brand_color: "#2cb34a"
