# markdown
highlighter: rouge
markdown: redcarpet
redcarpet:
  extensions:
  - smart
  - with_toc_data

exclude:
- ".ruby-version"
- ".jekyll-metadata"
- ".gitignore"
- ".travis.yml"
- todo.txt
- resources
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- CONTRIBUTING.md
- LICENSE.md

# Site metadata
name: The HTTPS-Only Standard
description: "Resources, best practices, and case studies for deploying HTTPS in the federal government."
url: https://https.cio.gov

# GitHub information
org_name: GSA
repo_name: https
branch: master

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: /
- text: Why Everything?
  url: /everything/
- text: Compliance Guide
  url: /guide/
- text: FAQ
  url: /faq/
- text: Strict Transport Security
  url: /hsts/
- text: Server Name Indication
  url: /sni/
- text: Technical Guidelines
  url: /technical-guidelines/
- text: Mixed Content
  url: /mixed-content/
- text: Migrating APIs
  url: /apis/
- text: Resources
  url: /resources/
