# Override in development.
baseurl: '/https'

exclude:
- ".rbenv-version"
- README.md
- CONTRIBUTING.md
- LICENSE.md

# markdown
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions:
  - with_toc_data

# Site metadata
name: HTTPS in Government
description: "Resources, best practices, and case studies for deploying HTTPS in the federal government."


# GitHub information
repo_name: https
branch: gh-pages
gh_org: GSA
site_url: https://gsa.github.io/https

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: ""
  internal: true
- text: Definitions
  url: definitions
  internal: true
- text: Tools
  url: tools
  internal: true
- text: Resources
  url: resources
  internal: true

# Style Variables
brand_color: "#2cb34a"
